"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/coat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Coat(props) {
  const { nodes, materials } = useGLTF('/models/coat.glb')
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} color="#cacaca" position={[1.5, 3, 1.5]} rotation={[-1.107, 0.421, 0]} />
      <primitive object={nodes.Joint} />
      <skinnedMesh geometry={nodes.body_1.geometry} material={materials.Material11763} skeleton={nodes.body_1.skeleton} />
      <skinnedMesh geometry={nodes.body_2.geometry} material={materials.Material11767} skeleton={nodes.body_2.skeleton} />
      <skinnedMesh geometry={nodes.body_3.geometry} material={materials.Material11771} skeleton={nodes.body_3.skeleton} />
      <skinnedMesh geometry={nodes.body_4.geometry} material={materials.Material11775} skeleton={nodes.body_4.skeleton} />
      <skinnedMesh geometry={nodes.eye_L_Node.geometry} material={materials.Material11782} skeleton={nodes.eye_L_Node.skeleton} />
      <skinnedMesh geometry={nodes.eye_R_Node.geometry} material={materials.Material11789} skeleton={nodes.eye_R_Node.skeleton} />
      <skinnedMesh geometry={nodes.eyelash_L_Node.geometry} material={materials.Material11795} skeleton={nodes.eyelash_L_Node.skeleton} />
      <skinnedMesh geometry={nodes.eyelash_R_Node.geometry} material={materials.Material11802} skeleton={nodes.eyelash_R_Node.skeleton} />
      <skinnedMesh geometry={nodes.tooth__Node.geometry} material={materials.Material11808} skeleton={nodes.tooth__Node.skeleton} />
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_16.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_17.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_18.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_19.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_20.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_21.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_22.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_23.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_24.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_25.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_26.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_27.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_28.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_29.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_30.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_31.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_32.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_33.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_34.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_35.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_36.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_37.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_38.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_39.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_40.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_41.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_42.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_43.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_44.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_45.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_46.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_47.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_48.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_49.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_50.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_51.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_52.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_53.geometry} material={materials['Default Buttonhole_351938']} />
      <mesh geometry={nodes.Cloth_mesh_54.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_55.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_56.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_57.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_58.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_59.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_60.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_61.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_62.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_63.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_64.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_65.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_66.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_67.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_68.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_69.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_70.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_71.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_72.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_73.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_74.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_75.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_76.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_77.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_78.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_79.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_80.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_81.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_82.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_83.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_84.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_85.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_86.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_87.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_88.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_89.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_90.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_91.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_92.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_93.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_94.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_95.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_96.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_97.geometry} material={materials['Default Buttonhole_351973']} />
      <mesh geometry={nodes.Cloth_mesh_98.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_99.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_100.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_101.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_102.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_103.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_104.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_105.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_106.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_107.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_108.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_109.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_110.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_111.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_112.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_113.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_114.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_115.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_116.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_117.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_118.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_119.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_120.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_121.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_122.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_123.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_124.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_125.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_126.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_127.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_128.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_129.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_130.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_131.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_132.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_133.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_134.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_135.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_136.geometry} material={materials.Coatweight_Wool_FCL1PSW002_351824} />
      <mesh geometry={nodes.Cloth_mesh_137.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_138.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_139.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_140.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_141.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_142.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_143.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_144.geometry} material={materials.Lining_351836} />
      <mesh geometry={nodes.Cloth_mesh_145.geometry} material={materials.Lining_351836} />
      <group position={[0.027, 1.1, 0.124]} rotation={[-1.448, -1.256, -2.808]} scale={[1, 0.745, 1]}>
        <mesh geometry={nodes._mesh.geometry} material={materials['Closure_button_2,5_351871']} />
        <mesh geometry={nodes._mesh_1.geometry} material={materials['Closure_button_2,5_351871']} />
      </group>
      <group position={[0.025, 1.236, 0.115]} rotation={[1.625, -1.323, 0.258]} scale={[1, 0.745, 1]}>
        <mesh geometry={nodes._mesh_2.geometry} material={materials['Closure_button_2,5_351871']} />
        <mesh geometry={nodes._mesh_3.geometry} material={materials['Closure_button_2,5_351871']} />
      </group>
      <group position={[0.006, 0.953, 0.133]} rotation={[-2.506, -1.035, 2.201]} scale={[1, 0.745, 1]}>
        <mesh geometry={nodes._mesh_4.geometry} material={materials['Closure_button_2,5_351871']} />
        <mesh geometry={nodes._mesh_5.geometry} material={materials['Closure_button_2,5_351871']} />
      </group>
      <group position={[-0.03, 1.249, 0.088]} rotation={[-2.737, -1.011, -1.261]} scale={[1, 0.745, 1]}>
        <mesh geometry={nodes._mesh_6.geometry} material={materials['Closure_button_2,5_351871']} />
        <mesh geometry={nodes._mesh_7.geometry} material={materials['Closure_button_2,5_351871']} />
      </group>
      <mesh geometry={nodes._mesh_8.geometry} material={materials.Screw_351906} position={[-0.197, 1.106, -0.066]} rotation={[-1.644, -1.291, -2.995]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_9.geometry} material={materials.Screw_351906} position={[-0.218, 1.007, -0.046]} rotation={[-3.089, -0.89, 1.85]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_10.geometry} material={materials.Screw_351906} position={[-0.224, 0.906, -0.032]} rotation={[3.114, -0.936, 1.631]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_11.geometry} material={materials.Screw_351906} position={[-0.223, 0.803, -0.022]} rotation={[3.12, -1.058, 1.594]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_12.geometry} material={materials.Screw_351906} position={[-0.221, 0.701, -0.012]} rotation={[-3.104, -1.307, 1.707]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_13.geometry} material={materials.Screw_351906} position={[-0.222, 0.6, -0.001]} rotation={[-3.134, -1.265, 1.695]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_14.geometry} material={materials.Screw_351906} position={[-0.22, 0.498, 0.01]} rotation={[3.137, -1.437, 1.603]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_15.geometry} material={materials.Screw_351906} position={[-0.215, 0.395, 0.011]} rotation={[0.026, -1.377, -1.541]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_16.geometry} material={materials.Screw_351906} position={[0.226, 1.108, -0.017]} rotation={[-2.981, 1.154, -1.988]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_17.geometry} material={materials.Screw_351906} position={[0.238, 1.007, 0.003]} rotation={[-3.044, 1.108, -1.881]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_18.geometry} material={materials.Screw_351906} position={[0.246, 0.906, 0.023]} rotation={[-3.035, 1.202, -1.868]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_19.geometry} material={materials.Screw_351906} position={[0.253, 0.805, 0.041]} rotation={[-3.041, 1.212, -1.856]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_20.geometry} material={materials.Screw_351906} position={[0.259, 0.703, 0.06]} rotation={[3.097, 1.051, -1.73]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_21.geometry} material={materials.Screw_351906} position={[0.26, 0.601, 0.079]} rotation={[3.012, 0.979, -1.577]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_22.geometry} material={materials.Screw_351906} position={[0.253, 0.499, 0.09]} rotation={[1.798, 1.499, -0.239]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_23.geometry} material={materials.Screw_351906} position={[0.243, 0.397, 0.083]} rotation={[0.163, 1.205, 1.499]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_24.geometry} material={materials.Screw_351906} position={[0.216, 1.102, -0.03]} rotation={[2.847, 0.745, 1.704]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_25.geometry} material={materials.Screw_351906} position={[0.227, 0.999, -0.02]} rotation={[2.794, 0.955, 1.679]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_26.geometry} material={materials.Screw_351906} position={[0.24, 0.899, -0.004]} rotation={[2.625, 1.284, 1.895]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_27.geometry} material={materials.Screw_351906} position={[0.252, 0.798, 0.011]} rotation={[0.629, 1.406, -2.329]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_28.geometry} material={materials.Screw_351906} position={[0.262, 0.697, 0.026]} rotation={[0.189, 1.089, -1.831]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_29.geometry} material={materials.Screw_351906} position={[0.268, 0.595, 0.041]} rotation={[0.127, 0.733, -1.716]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_30.geometry} material={materials.Screw_351906} position={[0.269, 0.494, 0.055]} rotation={[0.124, 0.517, -1.593]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_31.geometry} material={materials.Screw_351906} position={[0.25, 0.395, 0.069]} rotation={[0.363, 0.734, -2.193]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_32.geometry} material={materials.Screw_351906} position={[-0.194, 1.105, -0.078]} rotation={[0.19, -1.259, 1.8]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_33.geometry} material={materials.Screw_351906} position={[-0.209, 1.005, -0.063]} rotation={[2.524, -1.34, -1.931]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_34.geometry} material={materials.Screw_351906} position={[-0.217, 0.904, -0.049]} rotation={[0.77, -1.347, 2.311]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_35.geometry} material={materials.Screw_351906} position={[-0.219, 0.802, -0.039]} rotation={[0.438, -1.142, 2.012]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_36.geometry} material={materials.Screw_351906} position={[-0.219, 0.7, -0.03]} rotation={[0.363, -1.042, 1.974]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_37.geometry} material={materials.Screw_351906} position={[-0.218, 0.598, -0.021]} rotation={[0.322, -0.974, 1.884]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_38.geometry} material={materials.Screw_351906} position={[-0.216, 0.496, -0.011]} rotation={[0.292, -0.933, 1.893]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_39.geometry} material={materials.Screw_351906} position={[-0.215, 0.395, 0]} rotation={[0.178, -0.632, 1.733]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_40.geometry} material={materials.Screw_351906} position={[-0.308, 1.324, -0.149]} rotation={[-1.845, -1.15, -0.449]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_41.geometry} material={materials.Screw_351906} position={[-0.327, 1.216, -0.153]} rotation={[-0.817, -1.112, 0.859]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_42.geometry} material={materials.Screw_351906} position={[-0.342, 1.108, -0.143]} rotation={[-0.811, -1.091, 0.832]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_43.geometry} material={materials.Screw_351906} position={[-0.362, 1, -0.14]} rotation={[-0.876, -1.095, 0.897]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_44.geometry} material={materials.Screw_351906} position={[-0.38, 0.901, -0.101]} rotation={[-0.321, -0.37, 1.292]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_45.geometry} material={materials.Screw_351906} position={[-0.312, 1.326, -0.131]} rotation={[0.897, 1.18, 0.512]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_46.geometry} material={materials.Screw_351906} position={[-0.334, 1.22, -0.113]} rotation={[0.588, 1.102, 0.86]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_47.geometry} material={materials.Screw_351906} position={[-0.354, 1.114, -0.1]} rotation={[0.372, 0.918, 0.941]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_48.geometry} material={materials.Screw_351906} position={[-0.368, 1.005, -0.095]} rotation={[0.469, 1.032, 1.038]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_49.geometry} material={materials.Screw_351906} position={[-0.385, 0.9, -0.088]} rotation={[0.277, 1.043, 1.515]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_50.geometry} material={materials.Screw_351906} position={[0.376, 1.326, -0.02]} rotation={[2.166, -1.275, 0.793]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_51.geometry} material={materials.Screw_351906} position={[0.384, 1.218, -0.003]} rotation={[2.368, -1.194, 0.948]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_52.geometry} material={materials.Screw_351906} position={[0.393, 1.11, 0.015]} rotation={[2.395, -1.172, 0.983]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_53.geometry} material={materials.Screw_351906} position={[0.406, 1.002, 0.021]} rotation={[1.975, -1.28, 0.462]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_54.geometry} material={materials.Screw_351906} position={[0.418, 0.895, 0.031]} rotation={[0.272, -0.99, -1.375]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_55.geometry} material={materials.Screw_351906} position={[0.379, 1.326, -0.036]} rotation={[-1.451, 1.268, -0.175]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_56.geometry} material={materials.Screw_351906} position={[0.39, 1.216, -0.028]} rotation={[-1.35, 1.286, -0.34]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_57.geometry} material={materials.Screw_351906} position={[0.399, 1.108, -0.012]} rotation={[-1.447, 1.293, -0.275]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_58.geometry} material={materials.Screw_351906} position={[0.414, 1.001, -0.005]} rotation={[-0.737, 1.114, -0.959]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_59.geometry} material={materials.Screw_351906} position={[0.419, 0.895, 0.018]} rotation={[-0.268, 0.261, -1.568]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_60.geometry} material={materials.Screw_351906} position={[0.045, 0.936, 0.15]} rotation={[-0.03, 0.183, -1.529]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_61.geometry} material={materials.Screw_351906} position={[0.044, 0.993, 0.144]} rotation={[-0.035, -0.104, -1.582]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_62.geometry} material={materials.Screw_351906} position={[0.048, 1.05, 0.139]} rotation={[-0.233, -0.504, -1.796]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_63.geometry} material={materials.Screw_351906} position={[0.064, 1.162, 0.12]} rotation={[-0.551, -0.779, -1.401]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_64.geometry} material={materials.Screw_351906} position={[0.056, 1.106, 0.135]} rotation={[-0.599, -1.18, -2.188]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_65.geometry} material={materials.Screw_351906} position={[0.042, 1.163, 0.118]} rotation={[-2.678, -1.029, -0.8]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_66.geometry} material={materials.Screw_351906} position={[0.035, 1.107, 0.122]} rotation={[-0.291, -0.826, 1.487]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_67.geometry} material={materials.Screw_351906} position={[0.035, 1.05, 0.134]} rotation={[-0.123, -0.649, 1.63]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_68.geometry} material={materials.Screw_351906} position={[0.035, 0.936, 0.15]} rotation={[-0.186, -0.009, 1.548]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes._mesh_69.geometry} material={materials.Screw_351906} position={[0.035, 0.993, 0.143]} rotation={[-0.152, -0.333, 1.576]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes.Trim.geometry} material={materials['D-Ring_Small_443220']} position={[-0.208, 0.924, 1.474]} rotation={[-2.955, 0.134, -1.37]} scale={[2.421, 2.908, 7]} />
      <mesh geometry={nodes.Trim_1.geometry} material={materials['D-Ring_Small_443231']} position={[-0.196, 1.376, 1.489]} rotation={[2.993, 0.111, -1.58]} scale={[2.421, 2.908, 7]} />
      <mesh geometry={nodes.BindedTrim_832346.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832383.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832420.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832457.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832494.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832531.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832568.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832605.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832642.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832679.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832721.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832758.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832795.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832832.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832869.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832906.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832943.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_832980.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833017.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833054.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833096.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833133.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833170.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833207.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833244.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833281.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833318.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833355.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833392.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833429.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833471.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833508.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833545.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833582.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833619.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833656.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833693.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833730.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833767.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833804.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833903.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833940.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_833977.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834014.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834051.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834088.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834125.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834162.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834199.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834236.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834273.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834310.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834347.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834384.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834421.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834458.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834511.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834548.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834585.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834622.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834659.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834696.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834733.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834770.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834807.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834844.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834881.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834918.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834955.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_834992.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835029.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835066.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835133.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835170.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835207.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835244.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835281.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835318.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835355.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835392.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835429.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835466.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835503.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835540.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835577.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835614.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835651.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835688.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835725.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835762.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835799.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835836.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_835873.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836106.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836143.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836180.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836217.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836254.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836291.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836328.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836365.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836402.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836439.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836476.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836513.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836550.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836587.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836624.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836661.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836698.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836735.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836772.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836809.geometry} material={materials['Default Topstitch_352348']} />
      <mesh geometry={nodes.BindedTrim_836846.geometry} material={materials['Default Topstitch_352348']} />
    </group>
  )
}

useGLTF.preload('/public/models/coat.glb')
